name: rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - statsmodels
  - notebook
  - rise
  - nb_black
  - jupyter_contrib_nbextensions
  - arch
